FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY SERVICE_A/main.py ./SERVICE_A/main.py
COPY shared/ ./shared/
EXPOSE 8000
CMD ["uvicorn", "SERVICE_A.main:app", "--host", "0.0.0.0", "--port", "8000"]